name: Go
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:

  test:
    
    name: Running Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.24.0
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    
#    - name: Configure git for private modules
#      env:
#        TOKEN: ${{ secrets.TOKEN }}
#      run: git config --global url."https://YOUR_GITHUB_USERNAME:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Run Test
      run: go test ./... -race -cover -v
